version: '3'
services:

  laravel:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ../:/var/www/
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=myapp
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    networks:
      - app-network
    # command: sh -c "npm run dev ---host 0.0.0.0"

  db:
    image: mysql:8.0.33
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=myapp
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - app-network

  nginx:
    image: nginx:1.21.6-alpine
    volumes_from:
      - laravel
    ports:
      - 8080:80
      # - 5173:5173
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - app-network

  frontend:
      image: node:20-alpine3.16
      ports:
        - 3000:3000
      volumes:
        - ../:/var/www/
      working_dir: /var/www  
      networks:
        - app-network
      command: sh -c "ls -al && npm run dev"

volumes:
  db_data:


networks:
  app-network:
